{% set version = "1.5.7" %}

package:
  name: massren
  version: {{ version }}

source:
  url: https://github.com/laurent22/massren/archive/v{{ version }}.tar.gz
  sha256: 7e7dd149bd3364235247268cc684b5a35badd9bee22f39960e075c792d037a8c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-cgo') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - go-licenses
  host:
    - sqlite

test:
  commands:
    - massren --help

about:
  home: https://github.com/laurent22/massren
  license: MIT
  license_file:
    - README.md
    - license-files/
  summary: Easily rename multiple files using your text editor
  dev_url: https://github.com/laurent22/massren

extra:
  recipe-maintainers:
    - danielnachun
